### ISSUE TITLE
Login loses the past URL context

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#5621] opened 2024-08-01 06:24 UTC
Login loses context of the URL. This can happen when
- user clicks on a shared link and the user needs to login. The url context is lost after login and the homepage is served
- user clicks on a link from alerts and if it needs login
- any other reasons to re-login. Eg changes in jwt

**Comment by vikrantgupta25** [comment] 2024-08-01 06:33
this should solve most of the above mentioned use cases - https://github.com/SigNoz/signoz/pull/5604 , @rahulkeswani101 can verify once here

**Comment by rahulkeswani101** [comment] 2024-08-01 09:36
@ankitnayan We have covered the first two use cases already as mentioned by @vikrantgupta25 and for the third use case, I have raised the new PR(#5623).

**Comment by ankitnayan** [comment] 2024-08-01 10:36
I don't think it works for even the 1st two cases. Open an incognito with https://saasmonitor.us.signoz.cloud/dashboard/a82dee24-c9b9-4bed-bc70-a4392a5a0954?relativeTime=1d

**Comment by rahulkeswani101** [comment] 2024-08-01 11:06
@ankitnayan I think this will not work because the code is unavailable in prod yet(#5604 ).

**Comment by vikrantgupta25** [comment] 2024-08-01 16:38
@rahulkeswani101 i think the issue is with SSO as the changes were deployed in the morning by @prashant-shahi

**Comment by rahulkeswani101** [comment] 2024-08-02 05:12
> @rahulkeswani101 i think the issue is with SSO as the changes were deployed in the morning by @prashant-shahi

Yes, the changes were deployed to prod and the issue is with SSO only.

**Comment by vikrantgupta25** [comment] 2024-12-17 08:34
these issues are addressed in the new revamp here - https://github.com/SigNoz/signoz/pull/6598

**Comment by vikrantgupta25** [comment] 2024-12-21 10:36
this is done now

**Closed by vikrantgupta25** 2024-12-21 10:36 UTC
Labels: enhancement, frontend, navigation
