### ISSUE TITLE
FE: ability to duplicate widgets in a dashboard

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz#1940] opened 2022-12-28 22:57 UTC
## Is your feature request related to a problem?

Currently, users have to manually create every widgets manually.

## Describe the solution you'd like

There would be multiple cases where all attributes would be identical except the metrics name.
In those cases, the ability to duplicate widgets would be of much help.

Duplicate option in each widgets would be nice.

![image](https://user-images.githubusercontent.com/11138844/209882608-bbd4c545-71e3-47ca-98e4-6d86da5f051f.png)

## Describe alternatives you've considered

NA

## Additional context
NA

**Comment by palashgdev** [comment] 2022-12-29 05:10
Duplicate of https://github.com/SigNoz/signoz/issues/707

**Closed by palashgdev** 2022-12-29 05:10 UTC
