### ISSUE TITLE
Signoz logs CONTAINS keyword not working

### ISSUE THREAD

**Issue by abhinavramana** [SigNoz/signoz#2493] opened 2023-03-23 23:18 UTC
## Bug description
https://signoz.wombo.net/logs?q=otelServiceName%20CONTAINS%20%27paint%27 doesn't work : **otelServiceName CONTAINS 'paint'**

https://signoz.wombo.net/logs?q=otelServiceName%20IN%20(%27paint-service-backend-prod%27) works : **otelServiceName IN ('paint-service-backend-prod')**
## Expected behavior

Both should work

**Comment by srikanthccv** [comment] 2023-03-24 04:27
This is a known bug @nityanandagohain is looking into it — duplicate of #2428.

**Closed by srikanthccv** 2023-03-24 04:27 UTC
