### ISSUE TITLE
FE: Jitters in alerts creation page

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#5117] opened 2024-05-30 18:54 UTC
https://www.loom.com/share/8ecc35696b2543a48e2e88a7346147e0?sid=74d19cf8-9c2e-469b-b542-872d962a3a34

**Comment by ankitnayan** [comment] 2024-05-30 19:12
related https://github.com/SigNoz/engineering-pod/issues/1318

**Comment by vikrantgupta25** [comment] 2024-05-31 03:21
Duplicate of https://github.com/SigNoz/engineering-pod/issues/1318

**Closed by vikrantgupta25** 2024-05-31 03:21 UTC
Labels: bug, frontend, alerts
