### ISSUE TITLE
Alert graph legend format not working after save

### ISSUE THREAD

**Issue by patrijua** [SigNoz/signoz#2695] opened 2023-05-15 11:09 UTC
## Bug description

When I create a new metrics based alert using query builder, for example to monitor k8s_node_memory_available. I can define Legend Format as {{host_name}} so in graph legend I see node names nicely. This is working ok.

But, when I save the alert and re-open it, the legend in graph is like there would not be legend format defined at all.

## Expected behavior

I expect that when I define legend format  for graph and save the alert, after reopening the alert it would use the defined legend format

## Version information 
* **Signoz version**: v0.18.3
* **Browser version**: Chrome 113.0.5672.92
* **Your OS and version**: MacOS Ventura 13.1
* **Your CPU Architecture**(ARM/Intel): Intel

**Comment by srikanthccv** [comment] 2023-05-15 11:12
Duplicate of https://github.com/SigNoz/signoz/issues/2576

**Closed by srikanthccv** 2023-05-15 11:12 UTC
