### ISSUE TITLE
  Exceptions not registering in the main Exceptions page even though log page recognizes it

### ISSUE THREAD

**Issue by abhinavramana** [SigNoz/signoz#1691] opened 2022-11-05 03:49 UTC
**Describe your environment** 
Hosting on AWS, but reproducible in normal local Docker too

The exceptions page doesn't get populated with logger.error  compared to if we don't catch it.

![image](https://user-images.githubusercontent.com/4195703/200083418-1d25580d-2bb5-4b36-b181-51a2aad07998.png)
Even though the logs do show it
```
{
  "timestamp": 1667414082906112000,
  "id": "2GuSpuGSVeUBz0e5GPTdbPBHS1r",
  "trace_id": "dacf40c108535a20f92c9f758fa3a854",
  "span_id": "044228429cd2e18b",
  "trace_flags": 1,
  "severity_text": "ERROR",
  "severity_number": 17,
  "body": "(psycopg2.errors.InsufficientPrivilege) permission denied for table flags\n\n[SQL: INSERT INTO flags (id, entity_id, entity_type, flagging_reason, flagger, flagger_id, created_at, updated_at, deleted_at) VALUES (%(id)s, %(entity_id)s, %(entity_type)s, %(flagging_reason)s, %(flagger)s, %(flagger_id)s, %(created_at)s, %(updated_at)s, %(deleted_at)s) /*db_driver='psycopg2',db_framework='sqlalchemy%%3A0.34b0',traceparent='00-dacf40c108535a20f92c9f758fa3a854-d92a3bed78eddafb-01'*/]\n[parameters: {'id': UUID('ecf17dc6-68da-431f-a936-73e07d45ae2a'), 'entity_id': 3560, 'entity_type': 'art_gallery', 'flagging_reason': 'nudity_or_pornography', 'flagger': 'user', 'flagger_id': 'N2LDjSOuMhTp97JbIooskyVfT7H3', 'created_at': datetime.datetime(2022, 11, 2, 18, 34, 42, 901019), 'updated_at': datetime.datetime(2022, 11, 2, 18, 34, 42, 901020), 'deleted_at': None}]\n(Background on this error at: http://sqlalche.me/e/13/f405)",
  "resources_string": {
    "service_name": "paint-service-backend-prod",
    "telemetry_auto_version": "0.34b0",
    "telemetry_sdk_language": "python",
    "telemetry_sdk_name": "opentelemetry",
    "telemetry_sdk_version": "1.13.0"
  },
  "attributes_string": {
    "exception_message": "(psycopg2.errors.InsufficientPrivilege) permission denied for table flags\n",
    "exception_stacktrace": "Traceback (most recent call last):\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1276, in _execute_context\n    self.dialect.do_execute(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 593, in do_execute\n    cursor.execute(statement, parameters)\npsycopg2.errors.InsufficientPrivilege: permission denied for table flags\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/app/wombo/api/gallery/gallery.py\", line 142, in flag_artwork\n    flagged_artwork = gallery_service.flag_artwork(db, current_user.id, params.art_id, params.reason)\n  File \"/app/wombo/services/gallery_service.py\", line 276, in flag_artwork\n    db.commit()\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py\", line 1042, in commit\n    self.transaction.commit()\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py\", line 504, in commit\n    self._prepare_impl()\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py\", line 483, in _prepare_impl\n    self.session.flush()\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py\", line 2523, in flush\n    self._flush(objects)\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py\", line 2664, in _flush\n    transaction.rollback(_capture_exception=True)\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py\", line 68, in __exit__\n    compat.raise_(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py\", line 182, in raise_\n    raise exception\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py\", line 2624, in _flush\n    flush_context.execute()\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py\", line 422, in execute\n    rec.execute(self)\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py\", line 586, in execute\n    persistence.save_obj(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py\", line 239, in save_obj\n    _emit_insert_statements(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py\", line 1135, in _emit_insert_statements\n    result = cached_connections[connection].execute(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1011, in execute\n    return meth(self, multiparams, params)\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py\", line 298, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1124, in _execute_clauseelement\n    ret = self._execute_context(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1316, in _execute_context\n    self._handle_dbapi_exception(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1510, in _handle_dbapi_exception\n    util.raise_(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py\", line 182, in raise_\n    raise exception\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1276, in _execute_context\n    self.dialect.do_execute(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 593, in do_execute\n    cursor.execute(statement, parameters)\nsqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for table flags\n\n[SQL: INSERT INTO flags (id, entity_id, entity_type, flagging_reason, flagger, flagger_id, created_at, updated_at, deleted_at) VALUES (%(id)s, %(entity_id)s, %(entity_type)s, %(flagging_reason)s, %(flagger)s, %(flagger_id)s, %(created_at)s, %(updated_at)s, %(deleted_at)s) /*db_driver='psycopg2',db_framework='sqlalchemy%%3A0.34b0',traceparent='00-dacf40c108535a20f92c9f758fa3a854-d92a3bed78eddafb-01'*/]\n[parameters: {'id': UUID('ecf17dc6-68da-431f-a936-73e07d45ae2a'), 'entity_id': 3560, 'entity_type': 'art_gallery', 'flagging_reason': 'nudity_or_pornography', 'flagger': 'user', 'flagger_id': 'N2LDjSOuMhTp97JbIooskyVfT7H3', 'created_at': datetime.datetime(2022, 11, 2, 18, 34, 42, 901019), 'updated_at': datetime.datetime(2022, 11, 2, 18, 34, 42, 901020), 'deleted_at': None}]\n(Background on this error at: http://sqlalche.me/e/13/f405)\n",
    "exception_type": "ProgrammingError",
    "otelServiceName": "paint-service-backend-prod",
    "otelSpanID": "044228429cd2e18b",
    "otelTraceID": "dacf40c108535a20f92c9f758fa3a854"
  },
  "attributes_int": {},
  "attributes_float": {}
}
```

**Steps to reproduce**
Code sample: https://github.com/abhinavramana/trimmed-wombo-fastapi-signoz/blob/main/wombo/fastapi.py

1. Hit **exception_dont_works** endpoint
2. See it doesn't show the exception event associated with it, with results in the main signoz frontend not registering it as an exception  (see the image attached)
3. Go to logs page and see that signoz does suggest its an exception. 
4. Hit **exception_works** endpoint (it doesn't have try catch)
5. See it registers it in https://signoz.wombo.net/exceptions page .

**What is the expected behavior?**
We want to be able to see exceptions in logger.error for exception_dont_works  as a first class citizen in https://signoz.wombo.net/exceptions page as well.

**What is the actual behavior?**
We don't see them

**Additional context**
FastAPI is getting used

**Comment by srikanthccv** [comment] 2022-11-07 01:42
FYI: A log record with severity exception doesn't necessarily mean an exception on span event. In many cases exceptions are just caught and logged -- the trace may not have exception event depending how it's handled.

**Comment by pranay01** [comment] 2022-11-16 16:27
@abhinavramana Ok to close this? since trace exception event and exceptions in logger are different things?

More details on exception event - https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/exceptions/

**Comment by abhinavramana** [comment] 2022-11-16 17:58
@makeavish  Thanks the manual workaround I will try and see. However, I think that would again need lot of code changes all over the place. 

@pranay01 @srikanthccv The traceId is definitely associated with the exception , as you can see with the json I posted
```
{
  "timestamp": 1667414082906112000,
  "id": "2GuSpuGSVeUBz0e5GPTdbPBHS1r",
  "trace_id": "dacf40c108535a20f92c9f758fa3a854",
  "span_id": "044228429cd2e18b",
  "trace_flags": 1,
  "severity_text": "ERROR",
  "severity_number": 17,
  "body": "(psycopg2.errors.InsufficientPrivilege) permission denied for table flags\n\n[SQL: INSERT INTO flags (id, entity_id, entity_type, flagging_reason, flagger, flagger_id, created_at, updated_at, deleted_at) VALUES (%(id)s, %(entity_id)s, %(entity_type)s, %(flagging_reason)s, %(flagger)s, %(flagger_id)s, %(created_at)s, %(updated_at)s, %(deleted_at)s) /*db_driver='psycopg2',db_framework='sqlalchemy%%3A0.34b0',traceparent='00-dacf40c108535a20f92c9f758fa3a854-d92a3bed78eddafb-01'*/]\n[parameters: {'id': UUID('ecf17dc6-68da-431f-a936-73e07d45ae2a'), 'entity_id': 3560, 'entity_type': 'art_gallery', 'flagging_reason': 'nudity_or_pornography', 'flagger': 'user', 'flagger_id': 'N2LDjSOuMhTp97JbIooskyVfT7H3', 'created_at': datetime.datetime(2022, 11, 2, 18, 34, 42, 901019), 'updated_at': datetime.datetime(2022, 11, 2, 18, 34, 42, 901020), 'deleted_at': None}]\n(Background on this error at: http://sqlalche.me/e/13/f405)",
  "resources_string": {
    "service_name": "paint-service-backend-prod",
    "telemetry_auto_version": "0.34b0",
    "telemetry_sdk_language": "python",
    "telemetry_sdk_name": "opentelemetry",
    "telemetry_sdk_version": "1.13.0"
  },
  "attributes_string": {
    "exception_message": "(psycopg2.errors.InsufficientPrivilege) permission denied for table flags\n",
    "exception_stacktrace": "Traceback (most recent call last):\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1276, in _execute_context\n    self.dialect.do_execute(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 593, in do_execute\n    cursor.execute(statement, parameters)\npsycopg2.errors.InsufficientPrivilege: permission denied for table flags\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/app/wombo/api/gallery/gallery.py\", line 142, in flag_artwork\n    flagged_artwork = gallery_service.flag_artwork(db, current_user.id, params.art_id, params.reason)\n  File \"/app/wombo/services/gallery_service.py\", line 276, in flag_artwork\n    db.commit()\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py\", line 1042, in commit\n    self.transaction.commit()\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py\", line 504, in commit\n    self._prepare_impl()\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py\", line 483, in _prepare_impl\n    self.session.flush()\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py\", line 2523, in flush\n    self._flush(objects)\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py\", line 2664, in _flush\n    transaction.rollback(_capture_exception=True)\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py\", line 68, in __exit__\n    compat.raise_(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py\", line 182, in raise_\n    raise exception\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py\", line 2624, in _flush\n    flush_context.execute()\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py\", line 422, in execute\n    rec.execute(self)\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py\", line 586, in execute\n    persistence.save_obj(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py\", line 239, in save_obj\n    _emit_insert_statements(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py\", line 1135, in _emit_insert_statements\n    result = cached_connections[connection].execute(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1011, in execute\n    return meth(self, multiparams, params)\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py\", line 298, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1124, in _execute_clauseelement\n    ret = self._execute_context(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1316, in _execute_context\n    self._handle_dbapi_exception(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1510, in _handle_dbapi_exception\n    util.raise_(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py\", line 182, in raise_\n    raise exception\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py\", line 1276, in _execute_context\n    self.dialect.do_execute(\n  File \"/opt/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py\", line 593, in do_execute\n    cursor.execute(statement, parameters)\nsqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for table flags\n\n[SQL: INSERT INTO flags (id, entity_id, entity_type, flagging_reason, flagger, flagger_id, created_at, updated_at, deleted_at) VALUES (%(id)s, %(entity_id)s, %(entity_type)s, %(flagging_reason)s, %(flagger)s, %(flagger_id)s, %(created_at)s, %(updated_at)s, %(deleted_at)s) /*db_driver='psycopg2',db_framework='sqlalchemy%%3A0.34b0',traceparent='00-dacf40c108535a20f92c9f758fa3a854-d92a3bed78eddafb-01'*/]\n[parameters: {'id': UUID('ecf17dc6-68da-431f-a936-73e07d45ae2a'), 'entity_id': 3560, 'entity_type': 'art_gallery', 'flagging_reason': 'nudity_or_pornography', 'flagger': 'user', 'flagger_id': 'N2LDjSOuMhTp97JbIooskyVfT7H3', 'created_at': datetime.datetime(2022, 11, 2, 18, 34, 42, 901019), 'updated_at': datetime.datetime(2022, 11, 2, 18, 34, 42, 901020), 'deleted_at': None}]\n(Background on this error at: http://sqlalche.me/e/13/f405)\n",
    "exception_type": "ProgrammingError",
    "otelServiceName": "paint-service-backend-prod",
    "otelSpanID": "044228429cd2e18b",
    "otelTraceID": "dacf40c108535a20f92c9f758fa3a854"
  },
  "attributes_int": {},
  "attributes_float": {}
}```

**Comment by srikanthccv** [comment] 2022-11-21 13:04
> The problem manifests in the worse way as even when we throw manually HTTPException, signoz doesn't show it as an exception

The `ValueError` and `HTTPException` are _[handled](https://github.com/tiangolo/fastapi/blob/master/fastapi/exception_handlers.py#L10)_ hence they are not captured as a span [event](https://github.com/open-telemetry/opentelemetry-python/blob/74ced8508a71a263e56d92073af2498b7630978b/opentelemetry-api/src/opentelemetry/trace/span.py#L150). This is expected and by design from the OpenTelemetry SDK. 

> However, I think that would again need lot of code changes all over the place.

Here is small handler that does this automatically without much changes to your code
```python
import logging
from opentelemetry.trace import Status, StatusCode, get_current_span

class LogErrorHandler(logging.Handler):
    def emit(self, record):
        span = get_current_span()
        if span is not None:
            if record.exc_info is not None:
                exc_type, exc_value, tb = record.exc_info
                if exc_value is not None:
                    span.record_exception(exc_value)
            if record.levelno >= logging.ERROR:
                span.set_status(Status(StatusCode.ERROR, record.getMessage()))
```

> I can only see those exceptions (even If status is 500 with traces having exception_type etc. recognizing them) in logs if I explicitly search for them or user complains.

The existence of `attributes_string.exception_type` doesn't necessarily mean an exception to be concerned with in many cases. The subtle difference between handled exceptions (i.e., expected) vs unhandled exceptions (something gone wrong and unexpected that needs attention).

@pranay01 It's worth looking at the severity of the log record and add any record above the threshold as an exception event.

**Comment by abhinavramana** [comment] 2022-11-21 21:08
@srikanthccv https://github.com/abhinavramana/trimmed-wombo-fastapi-signoz/blob/main/wombo/logger_stuff.py#L20 I did as you mentioned but its still not showing the missing excpetions

**Comment by srikanthccv** [comment] 2022-11-22 03:37
> still not showing the missing exceptions

What are these missing exceptions you are referring to? I could see the `ValueError` from the route `/exception_dont_works`

<img width="1239" alt="Screenshot 2022-11-22 at 9 06 06 AM" src="https://user-images.githubusercontent.com/22846633/203215295-9109a0d5-7925-40d9-8852-1ccb78b4b242.png">

**Comment by abhinavramana** [comment] 2022-11-23 17:18
Hmm, I had to remove  `if record.levelno >= logging.ERROR:` but it works now

**Comment by abhinavramana** [comment] 2022-11-23 17:33
I see them coming duplicated though

![image](https://user-images.githubusercontent.com/4195703/203612016-d7b9dab9-8dba-4cfe-9149-31ea0601e673.png)
![image](https://user-images.githubusercontent.com/4195703/203612081-7406678b-4a2b-4512-9aad-39b612c8b0ec.png)

**Comment by makeavish** [comment] 2022-11-24 01:15
@abhinavramana We are aggregating with exception type and error message. As you can see, that error message is different in both cases.

**Comment by makeavish** [comment] 2022-11-25 02:23
@abhinavramana Closing the issue as it seems original issue is resolved. If you are facing any other issue, feel free to open a new issue or if the same issue is encountered again, then reopen this issue.

**Closed by makeavish** 2022-11-25 02:23 UTC
Labels: exceptions
