### ISSUE TITLE
Sorting doesn't works as expected with date columns

### ISSUE THREAD

**Issue by ishan123456789** [SigNoz/signoz#1615] opened 2022-10-06 07:56 UTC
## Bug description
No matter if I try toggle ascending/descending the sorting doesn't happen
![Screenshot 2022-10-06 at 1 24 30 PM](https://user-images.githubusercontent.com/23247168/194249793-7130af2e-8295-4fbd-b4c7-b4e32fba0308.png)

## Expected behavior
Sorting on date column should work similar to the other columns

## How to reproduce

1. Go to traces page
2. Try to click on Date
3. See that sorting doesn't change

## Version information 
* **Signoz version**: v0.11.1
* **Browser version**: Version 105.0.5195.125 (Official Build) (x86_64)
* **Your OS and version**: MAC
* **Your CPU Architecture**(ARM/Intel): Intel

**Comment by makeavish** [comment] 2022-10-07 06:44
@ishan123456789 This is due to [bug in clickhouse](https://github.com/ClickHouse/ClickHouse/issues/37673) projections. It is caused by duplicate entries in a table.
It was [fixed](https://github.com/ClickHouse/ClickHouse/pull/38725) by Clickhouse and released in 22.8 LTS version. Currently signoz is using 22.4 clickhouse image so this bug still exists. For now, you can run the below query to deduplicate rows to fix this temporarily after [connecting to clickhouse](https://signoz.io/docs/operate/clickhouse/connect-to-clickhouse/).
Query: `OPTIMIZE TABLE signoz_traces.signoz_index_v2 FINAL DEDUPLICATE;`
@prashant-shahi We need to update to clickhouse 22.8 LTS version for signoz.

**Comment by makeavish** [comment] 2022-10-07 06:50
Can be closed after https://github.com/SigNoz/signoz/issues/1618 is closed.

**Closed** 2022-11-16 11:12 UTC
