### ISSUE TITLE
Is there chaining in dashboard variables?

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1955] opened 2023-01-02 18:14 UTC
are the dashboard variables dependent on previous variables? Say I have `App Name` and `Instance`, surely I don't want to show all instances of all apps!

[Slack Message](https://signoz-community.slack.com/archives/C01HWUTP4HH/p1672681832494029?thread_ts=1672681832.494029&cid=C01HWUTP4HH)

**Comment by ankitnayan** [comment] 2023-01-03 18:00
duplicate of https://github.com/SigNoz/signoz/issues/1973

**Closed** 2023-01-04 04:56 UTC
Labels: slack community
