### ISSUE TITLE
In product feedback button appears cut off and remains like that when switched back to dark mode

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#453] opened 2021-12-03 19:54 UTC
## Bug description

In product feedback button in light mode appears cut off. Screen shot below

![Image 04-12-2021 at 1 17](https://user-images.githubusercontent.com/504541/144664078-6a6b25ae-2470-4b8a-9a17-1ad2f0dd0e51.jpg)

## Expected behavior

It should appear as a rounded rectangle button with icon as in the dark mode. Attached video

![Screen Recording 04-12-2021 at 1 23](https://user-images.githubusercontent.com/504541/144664742-576be690-fafa-4553-8007-44aab1f4e5ff.gif)

## How to reproduce

1. Open SigNoz UI
2. Go to any page after giving initial email and name
3. You should see the button in the bottom right corner

## Version information 
* **Signoz version**: v0.5.2
* **Browser version**: Version 96.0.4664.55 (Official Build) (arm64)
* **Your OS and version**: macOS Moneterey

**Comment by atharva137** [comment] 2021-12-04 18:34
hello, can I work on this issue?

**Comment by pal-sig** [comment] 2021-12-04 18:37
> hello, can I work on this issue?

Sure

**Comment by atharva137** [comment] 2021-12-04 20:02
@pal-sig  can you please provide me  test-environment-url for setting up a local environment  and also I had  dm on #contributing on the slack community for the same 

Thanks and Regards 
Atharva Yawalkar

**Comment by pal-sig** [comment] 2021-12-05 10:26
> @pal-sig can you please provide me test-environment-url for setting up a local environment and also I had dm on #contributing on the slack community for the same
> 
> Thanks and Regards Atharva Yawalkar

Shared

**Comment by atharva137** [comment] 2021-12-05 21:38
Hello @pal-sig I feel sorry as  I'm unable to figure out the solution for the feedback button

**Comment by Anurag5086** [comment] 2021-12-06 06:45
@pranay01 @pal-sig Actually the problem is that when we are changing to light mode, the css classes clash and properties which are mentioned in the styled components are not being used, instead the classes on ant-design of light mode is taking over. 

![image](https://user-images.githubusercontent.com/54763478/144799958-32786bde-e97e-451c-a13e-9a59535bb0e0.png)

So this is the solution which i came up for now, as the attributes of height, width and border-radius in the light mode are clashing with ant-design light theme button class.

If this sounds good i can raise a PR.

**Comment by architgarg603** [comment] 2021-12-08 15:09
can i work on this issue ?

**Comment by govind2404** [comment] 2021-12-09 06:03
I would like to work on this issue. Assign this to me.

**Closed** 2021-12-10 07:59 UTC
Labels: good first issue, frontend
