### ISSUE TITLE
Service Map view does not work

### ISSUE THREAD

**Issue by patrijua** [SigNoz/signoz#2941] opened 2023-06-20 15:20 UTC
## Bug description

After upgrading from v0.18.0 to V0.20.2 Service Map view fails to visualize services. 

![image](https://github.com/SigNoz/signoz/assets/57624530/fcfa3a4b-ceeb-462c-945e-a0c032f3e263)

When I start to type into text box "deployment.environment IN" then it does suggest me namespaces and I can select one it suggest but it fails to visualize anything. So in screenshot it did suggest me "staging" as one of the option from many others also.

If I dont give any filter, it does visualize two of my services but I have have no idea in what namespace they are or why it does show those two and only those two even thought I have a lot more services.

In "Service" view and also in "Traces" view I can use the same deployment.environment resource filter to filter services and traces just fine so those views are working ok. In those views I can see all of my services just fine.

## Expected behavior

I expect that I can use resource filter to services by namespace in Service Map view.

## Version information 
* **Signoz version**: v0.20.2
* **Browser version**: Chrome Version 114.0.5735.133
* **Your OS and version**: MacOS Ventura 13.1
* **Your CPU Architecture**(ARM/Intel): Intel

**Comment by srikanthccv** [comment] 2023-06-20 22:26
>If I dont give any filter, it does visualize two of my services but I have have no idea in what namespace they are or why it does show those two and only those two even thought I have a lot more services

When no filtering is applied, all the services are shown. You might have to zoom out a little bit if there are a lot more services. Do all of your services have `deployment.environment` set?

I couldn't reproduce this. I added a demo application with `deployment.environment=demo` and could see the service map. One thing I want to highlight here is the map doesn't work for single standalone service.

**Comment by pranay01** [comment] 2024-12-12 06:06
Closing - Can't reproduce

**Closed by pranay01** 2024-12-12 06:06 UTC
Labels: service-map
