### ISSUE TITLE
Logs Detail JSON U/X: Improve how json is show in detail page.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#3301] opened 2023-08-09 16:40 UTC
As of now we render it as
```
{
  "attributes_float64": {},
  "attributes_int64": {},
  "attributes_string": {
    "container_id": "debian",
    "container_name": "hotrod"
  },
  "body": "2023-08-09T16:33:00.956Z\tERROR\tdriver/server.go:85\tRetrying GetDriver after error\t{\"service\": \"driver\", \"trace_id\": \"5a10fe6fe4c2607f\", \"span_id\": \"0e27247a1e125208\", \"retry_no\": 1, \"error\": \"redis timeout\"}",
  "id": "2Thvbvnwkf3OowdELzA7SUxMEFx",
  "resources_string": {},
  "severity_number": 0,
  "severity_text": "",
  "span_id": "",
  "trace_flags": 0,
  "trace_id": "",
  "timestamp": "2023-08-09T16:33:00Z"
}
```

we need to change it to
```
{
  "attributes": {
    "container_id": "debian",
    "container_name": "hotrod"
  },
  "body": "2023-08-09T16:33:00.956Z\tERROR\tdriver/server.go:85\tRetrying GetDriver after error\t{\"service\": \"driver\", \"trace_id\": \"5a10fe6fe4c2607f\", \"span_id\": \"0e27247a1e125208\", \"retry_no\": 1, \"error\": \"redis timeout\"}",
  "id": "2Thvbvnwkf3OowdELzA7SUxMEFx",
  "resources": {},
  "severity_number": 0,
  "severity_text": "",
  "span_id": "",
  "trace_flags": 0,
  "trace_id": "",
  "timestamp": "2023-08-09T16:33:00Z"
}
```

So we are keeping just `attributes` and `resources` instead of their types.

**Comment by palashgdev** [comment] 2023-09-15 08:56
Duplicate of https://github.com/SigNoz/signoz/issues/3276

**Closed by palashgdev** 2023-09-15 08:56 UTC
Labels: logs detail
