### ISSUE TITLE
Dashboard Variables: Test Query runs on saved queries and not Text input

### ISSUE THREAD

**Issue by saadbahir** [SigNoz/signoz#4195] opened 2023-12-08 12:58 UTC
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

If you click on `Test Run Query` => it runs on the saved query and **NOT** the latest text input

<img width="1164" alt="Screenshot 2023-12-08 at 16 50 09" src="https://github.com/SigNoz/signoz/assets/115225167/82e4fcfd-0c24-4962-823e-f6289765c015">

## Expected behavior

If I change the text input in the `Query` block and I click on `Test Run Query`, it should execute that query 

## How to reproduce

1. Go to Dashboards
2. Open a dashboard
3. Click on `Configure` button
4. Click on `Variables` tab
5. Enter a query and save
6. Open the variable again
7. Change the query
8. Click on `Test Run Query`
9. Verify the query sent to the backend through the Network

## Version information 
* **Signoz version**: 0.35.0   
* **Browser version**: Version 119.0.6045.199 (Official Build) (arm64)
* **Your OS and version**: OS Venture 13.3.1 (22E261)
* **Your CPU Architecture**(ARM/Intel):  ARM

**Comment by pranay01** [comment] 2023-12-08 13:31
thanks for reporting this @saadbahir We will have a look

**Comment by pranay01** [comment] 2023-12-08 13:31
@YounixM Can you check if it's a frontend issue

**Comment by YounixM** [comment] 2023-12-08 17:37
@pranay01 : Yes, this is a bug, it's already fixed and will be released in the next release.

**Comment by pranay01** [comment] 2023-12-18 08:00
@YounixM if this is fixed, can we close the issue?

Might be good to link the issue with PRs also, so that when corresponding PRs are merged, the issue is automatically closed

**Comment by YounixM** [comment] 2023-12-18 08:21
Yes @pranay01, this is fixed.

https://github.com/SigNoz/signoz/pull/4210

Will make sure to tag the issue in PRs so that it can be auto-closed.

**Closed by YounixM** 2023-12-18 08:21 UTC
Labels: dashboards

**Comment by pranay01** [comment] 2023-12-18 12:33
thanks.
