### ISSUE TITLE
Allow custom aggregation interval

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#4653] opened 2024-03-05 19:52 UTC
SigNoz auto determines aggregation interval based on global time period. But sometimes when the user wants to aggregate every hour/day/week it is not possible to edit aggregation interval.
<img width="496" alt="Screenshot 2024-03-06 at 01 21 55" src="https://github.com/SigNoz/signoz/assets/9512100/77c40d5b-b1c4-4849-a878-d9287f9450c7">

**Comment by srikanthccv** [comment] 2024-03-06 01:25
Duplicate of https://github.com/SigNoz/signoz/issues/4631

**Closed by srikanthccv** 2024-03-06 01:25 UTC
Labels: query-builder, customer demand
