### ISSUE TITLE
Trace details screen UI bug

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#531] opened 2021-12-16 10:34 UTC
## Bug description
On the trace details screen the errors tab has hamburger menu which opens errors. 

<img width="1403" alt="Screenshot 2021-12-16 at 15 54 00" src="https://user-images.githubusercontent.com/9512100/146355373-2ed79b00-1b8d-471a-afd4-0c78dc1773b8.png">

## Expected behavior
There should not be any hamburger menu

<img width="1421" alt="Screenshot 2021-12-16 at 15 54 14" src="https://user-images.githubusercontent.com/9512100/146354788-86303b24-be93-4a22-b168-c1e7d334d786.png">

## How to reproduce

1. Open Trace details page on Firefox

## Version information 
* **Signoz version**: 0.5.3
* **Browser version**: Firefox 95.0
* **Your OS and version**: MacOS 12.1

## Additional context
Only happening on Firefox, it is working fine on safari and chrome

**Comment by aryanshridhar** [comment] 2021-12-17 14:03
Looking into it!

**Comment by aryanshridhar** [comment] 2021-12-17 19:38
That's kind of surprising! I recreated the component here to check if it's an upstream issue, but in vain.
Link to sandbox - https://codesandbox.io/s/angry-sun-kf9bg?file=/src/index.js

**Comment by pranay01** [comment] 2021-12-17 19:40
@aryanshridhar So this issue is not getting reproduced in Firefox?

**Comment by aryanshridhar** [comment] 2021-12-18 07:28
@pranay01 The issue is reproduced in Firefox but I am not sure what is the exact reason. I thought that the issue is with [ant-design](https://github.com/ant-design/ant-design), but like I mentioned above - it isn't.

**Comment by aryanshridhar** [comment] 2021-12-18 07:30
Probably a second way to get around this issue is to - use a media query to handle the display property. (Will crerate a pr for better discussions)

**Comment by pranay01** [comment] 2021-12-18 07:33
ok - @pal-sig any thoughts on why this is happening, though there seems to be no underlying issue with antd

**Comment by pal-sig** [comment] 2021-12-20 05:00
@aryanshridhar i don't think overwriting existing Antd component css style would be a good solution for this one

**Comment by aryanshridhar** [comment] 2021-12-20 13:18
Yup felt like it because instead fixing the root cause, I was modifying the antd css styles. Any ideas why is this behavior taking place @pal-sig ?

**Comment by pal-sig** [comment] 2021-12-21 05:52
> Yup felt like it because instead fixing the root cause, I was modifying the antd css styles. Any ideas why is this behavior taking place @pal-sig ?

That still needs to be figured out....

**Comment by pranay01** [comment] 2022-03-03 14:06
fixed by https://github.com/SigNoz/signoz/pull/764 - Updated trace detail page design

**Closed by pranay01** 2022-03-03 14:06 UTC
Labels: bug, frontend, ui, flamegraph
