### ISSUE TITLE
API key management for different team

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#4213] opened 2023-12-12 12:47 UTC
Customers want to give different API key for different teams - and based on that they want to understand the amount of data sent and the cost incurred by each team?

[v1] Also, feature to add new API key, revoke old API keys, delete keys
[v2] So for each API key - we should show, the GBs of traces &amp; logs sent, # of samples sent for metrics, and also the cost incurred by each API key.
[v3] Alerts on cost/data sent

[Slack Message](https://signoz-team.slack.com/archives/C050MERV57W/p1701331495249589?thread_ts=1701271638.723949&cid=C050MERV57W)

**Comment by GeekBoySupreme** [comment] 2024-03-27 09:51
Updates for v2 :
<img width="854" alt="image" src="https://github.com/SigNoz/signoz/assets/15321738/bd295aa0-6b21-4a4a-b572-dfdf6f269955">
Find this on [Figma](https://www.figma.com/proto/EgkXVTQCosEQBfNB27YNKo/Signoz-Interface?page-id=2637%3A3568&type=design&node-id=2639-2303&viewport=715%2C267%2C0.11&t=IUUqOigKrZS8t9bv-1&scaling=min-zoom&starting-point-node-id=2639%3A2303&mode=design)

**Comment by grandwizard28** [comment] 2024-05-21 09:58
@YounixM finally found it

**Comment by grandwizard28** [comment] 2024-05-21 10:00
Duplicate of https://github.com/SigNoz/engineering-pod/issues/1020

**Comment by YounixM** [comment] 2024-06-04 12:39
PR: https://github.com/SigNoz/signoz/pull/5105

**Closed** 2024-06-04 13:10 UTC
Labels: enhancement, saas
