### ISSUE TITLE
Dashboard layout changes are not saved correctly

### ISSUE THREAD

**Issue by prashant-shahi** [SigNoz/signoz#729] opened 2022-02-15 17:39 UTC
## Bug description

The order of charts were changed with some charts taking up whole rows on centre.

Refreshing the page, I notice layouts changed randomly.

![Screenshot from 2022-02-15 23-01-25](https://user-images.githubusercontent.com/11138844/154117046-9f369692-a3ef-482a-a673-df51f44a6826.png)

## Expected behavior

Dashboard retaining position changes of charts.

## How to reproduce

1. Create some charts (more than 4) in a dashboard.
2. Change the order and save layout.
3. Refresh the page

## Version information 
* **Signoz version**: `v0.6.1`
* **Browser version**: `Brave version: 1.35.100  Chromium: 98.0.4758.87 (Official Build)  (64-bit)`
* **Your OS and version**: `Ubuntu 20.04.1`

**Comment by pranay01** [comment] 2022-02-17 07:50
@palash-signoz Can this be taken in the current sprint after trace detail page?

**Comment by palash-signoz** [comment] 2022-02-22 05:28
> @palash-signoz Can this be taken in the current sprint after trace detail page?

yes @pranay01 we can take this up after trace detail page

**Comment by ankitnayan** [comment] 2022-03-08 06:50
duplicate of #793

**Closed by ankitnayan** 2022-03-08 06:50 UTC
