### ISSUE TITLE
Preserve logs list view state/options

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#3050] opened 2023-07-06 10:39 UTC
The options of the list view should be saved to browser local storage. This includes the format of the list, max lines and added columns.

<img width="1232" alt="Screenshot 2023-07-06 at 16 09 00" src="https://github.com/SigNoz/signoz/assets/9512100/e575392c-3963-4c6b-bb98-95bb3fbd7280">

**Comment by nityanandagohain** [comment] 2023-07-06 11:55
duplicate of https://github.com/SigNoz/signoz/issues/3041

**Closed** 2023-07-06 15:56 UTC
Labels: frontend, logs-explorer
