### ISSUE TITLE
Metric Name suggestions in the dashboard not working

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#3218] opened 2023-07-27 18:03 UTC
When typing the metric name in the dashboard Query Builder, the UI does not show the suggestions received from the API call and hence it becomes very difficult for the user to choose the right metric name for filtering.

https://www.loom.com/share/6c3e72082d904c34a40f8a5b677ff93d?sid=35fad54f-12f8-45f7-b06e-b99a3334a728

**Comment by srikanthccv** [comment] 2023-07-28 02:44
Duplicate of #3217

**Closed by srikanthccv** 2023-07-28 02:44 UTC
Labels: bug, frontend, dashboards
