### ISSUE TITLE
[Bug]: Getting blank screen on click of view button of widget.

### ISSUE THREAD

**Issue by techchintan** [SigNoz/signoz#2471] opened 2023-03-20 10:57 UTC
![image](https://user-images.githubusercontent.com/46838508/226320007-4597a82d-fdd1-4f15-bc57-cce2ed9bd166.png)

**Comment by palashgdev** [comment] 2023-03-20 12:44
duplicate of https://github.com/SigNoz/signoz/issues/2450

**Closed by palashgdev** 2023-03-20 12:44 UTC
Labels: bug, good first issue, frontend, dashboards
