### ISSUE TITLE
Too much information in current logs UI 

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#1864] opened 2022-12-16 09:56 UTC
The current logs UI display's too much information which makes it difficult to go through logs.

Something like logs UI on Kibana is much helpful which looks like tailing on the application log.

**Comment by nityanandagohain** [comment] 2022-12-16 09:56
related issue https://github.com/SigNoz/signoz/issues/1848

**Comment by palashgdev** [comment] 2023-02-02 11:35
Duplicate of #1848

**Closed by palashgdev** 2023-02-02 11:35 UTC
