### ISSUE TITLE
`+` Operator in Formula is not working correctly

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2989] opened 2023-06-28 08:06 UTC
Video explanation: https://share.vidyard.com/watch/A7thjnJgtzaQUTwcGaLpt4?

**Comment by Rajat-Dabade** [comment] 2023-06-30 12:17
Not able to reproduce this issue on the `develop` branch. I guess the issue is already been fixed. Closing this issue.

**Closed by Rajat-Dabade** 2023-06-30 12:17 UTC
Labels: bug, frontend
