### ISSUE TITLE
`Application metrics`, `external calls` and `database calls` get expanded across entire screen

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#535] opened 2021-12-18 09:21 UTC
The tabs of `application metrics`, `external calls` and `database calls` on the application page get expanded across the entire screen sometimes. 
<img width="1238" alt="Screenshot 2021-12-18 at 2 47 12 PM" src="https://user-images.githubusercontent.com/83692067/146636124-a15262f6-1c66-45c9-9cd2-ba5af554e944.png">

Expected UI
<img width="1234" alt="Screenshot 2021-12-18 at 2 50 07 PM" src="https://user-images.githubusercontent.com/83692067/146636131-ba9ecaec-bb7a-48a8-8035-324f1a2b2b10.png">

**Comment by pranay01** [comment] 2021-12-18 13:44
Duplicate of https://github.com/SigNoz/signoz/issues/250 - same underlying issues with antd tabs

This PR https://github.com/SigNoz/signoz/pull/507 should fix this

**Comment by pal-sig** [comment] 2021-12-20 03:42
Closing in favour of duplicate issue #250

**Closed by pal-sig** 2021-12-20 03:42 UTC
Labels: frontend, application-metrics-page
