### ISSUE TITLE
Questions on understanding alert behavior

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1696] opened 2022-11-08 04:52 UTC
From Mariano Mirabelli in Slack community
--
Hi there

I have a question related to the alerts behaviour. Even though I have configured alerts without any trouble, when the alert state should go back from Firing to Ok, it tends to suffer much delay in comparison with the actual application state. I have developed the following example in my localhost to manage a  controlled environment:

• I have coded a little kotlin application with two fake endpoints: one that always returns HTTP 200 and another always returns HTTP 500.
• I configured an alert based on the PromQL query that SigNoz executes to retrieve the error percentage in the application dashboard. In my example, I was interested in measuring the error percentage in the last five minutes.
• I started a load test for 25 minutes against the 200 ok HTTP endpoint. At the same time, I ran a load test for 40 seconds against the 500 error HTTP endpoint.
• With that scenario, I achieve an error rate of around the 18%.
• Under these conditions, I observed that the alert state went from Ok to firing as I expected. In the same way, I received a slack notification notifying me that the alert was triggered.
• However, even though my application error percentage returned to 0 again and more than five minutes elapsed, the alert state kept on firing. The alert state returned to Ok after 30 minutes approximately.
Could you help me to understand what is happening?

I copy here the query that I’m running to trigger the alert:
```max(sum(rate(signoz_calls_total{service_name="ktor-test", operation=~`HTTP GET|HTTP POST`, status_code="STATUS_CODE_ERROR"}[5m]) OR rate(signoz_calls_total{service_name="ktor-test", operation=~`HTTP GET|HTTP POST`, http_status_code=~"5.."}[5m]))*100/sum(rate(signoz_calls_total{service_name="ktor-test", operation=~`HTTP GET|HTTP POST`}[5m]))) &lt; 1000 OR vector(0)```
And my condition on the Alert are the following:

• Send a notification when the metric is: *above*
• the threshold: *at least once*
• Alert Threshold: *5*
*Thanks in advance!*

[Slack Message](https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1667848206036309?thread_ts=1667848206.036309&cid=C01HWQ1R0BC)

**Comment by mindhash** [comment] 2022-11-09 06:57
The alerting module has two components:
- alert generation
- alert delivery 

**Alert generation**
The alert statuses (firing, resolved) are generated as a result of query execution. This part is handled by query service. The basic principle is - if a query results stops producing a row (lets call this target row), it is assumed that the alert is no longer active.  

The alert queries are executed every minute.  The query is always targeted for a small time period.  So when a user chooses condition like `when alert threshold is above x for last 5 minutes`, the alerting module appends a timeframe condition in the user query. The behaviour of threshold condition (e.g. `above x`) depends on the type of query. For promQL expressions, we just append the expression with the condition. For e.g. 
 
`http_requests_total{job="apiserver", handler="/api/comments"}[5m]`

would be appended with threshold condition before execution. The final query would look like -

`http_requests_total{job="apiserver", handler="/api/comments"}[5m] **> x**`

> note: If alerting threshold condition is not set, then the above query modification does not take place

The generated alerts are sent to alert manager at regular intervals as long as they are still active. When an alert is resolved (the target row no longer appears in query result), the same status is sent to alert manager.  

**Alert delivery**
The prior section applies to generation of alert and respective status.  There is another component to the alerting - sending the alert. 

The sending of alerts is performed by alert manager. If you do `docker ps` or `kubectl get pods -n <signoz namespace>`, you would notice a container or pod of alert manager running. This service is responsible for not just sending alert but reducing the noise. You don't want to keep getting alerts every minute. So alerting module - groups the alerts and sends in the intervals. The default is 5m.

This setup also accounts for network delay or failures. So if alert manager does not receive any status of alert for more than 5 mins, it assumes the alert is resolved.  

Hope this clarifies how alerts work internally.  Regarding the issue at hand, the problem is likely due to the way alerting module appends threshold condition.   

`max(sum(rate(signoz_calls_total{service_name="ktor-test", operation=~`HTTP GET|HTTP POST`, status_code="STATUS_CODE_ERROR"}[5m]) OR rate(signoz_calls_total{service_name="ktor-test", operation=~`HTTP GET|HTTP POST`, http_status_code=~"5.."}[5m]))*100/sum(rate(signoz_calls_total{service_name="ktor-test", operation=~`HTTP GET|HTTP POST`}[5m]))) &lt; 1000 OR vector(0)`

becomes 

`max(sum(rate(signoz_calls_total{service_name="ktor-test", operation=~`HTTP GET|HTTP POST`, status_code="STATUS_CODE_ERROR"}[5m]) OR rate(signoz_calls_total{service_name="ktor-test", operation=~`HTTP GET|HTTP POST`, http_status_code=~"5.."}[5m]))*100/sum(rate(signoz_calls_total{service_name="ktor-test", operation=~`HTTP GET|HTTP POST`}[5m]))) &lt; 1000 OR vector(0) **> 5**`

I need some more tests to confirm this, but it is likely that the **>** in appended threshold condition is taking precedence over **OR**.  Adding brackets around the promql expression could solve the problem. If this works, we can change alerting module to always include promql expr in brackets, so user doesn't have to.

**Comment by mindhash** [comment] 2022-11-10 15:24
The issue is resolved. Closing the ticket.

**Closed by mindhash** 2022-11-10 15:24 UTC
Labels: alerts, slack community
