### ISSUE TITLE
Deploy with helm chart on AWS

### ISSUE THREAD

**Issue by bartoszkosciug** [SigNoz/signoz#1255] opened 2022-06-13 19:39 UTC
## Bug description
Cant run the signoz on the AWS, the problem is that chi-signoz-cluster dont want to run:
![image](https://user-images.githubusercontent.com/97445164/173431268-68e9191d-d060-49ea-b260-373823139575.png)
![image](https://user-images.githubusercontent.com/97445164/173431309-d24ae776-f4d9-4adb-b25b-db660bd21124.png)

## Expected behavior
The expected behavior is that helm chart is deployed with success - all pods are running. 

## How to reproduce

1. Create override-values.yaml file
clickhouse:
  cloud: aws
  installCustomStorageClass: true
  persistence:
    storageClass: gp2-resizable
3. helm repo add signoz https://charts.signoz.io
4. kubectl create ns platform
5. helm --namespace platform install my-release signoz/signoz -f override-values.yaml

## Version information 
N/A

## Additional context
N/A

**Comment by AkshayAwate** [comment] 2022-07-12 15:03
can you provide logs of pod `kubectl logs <chi-pod> `or please paste the output of `kubectl describe pod <chi-pod-name>` ? @bartoszkosciug

**Comment by prashant-shahi** [comment] 2022-07-12 16:29
@AkshayAwate Thanks for the message in the thread. It turns out that I missed out on it.

@bartoszkosciug we have updated quite a lot of things in charts recently. As Akshay stated logs and pod state would be very helpful.

**Comment by prashant-shahi** [comment] 2022-10-31 14:09
Not able to replicate the issue in EKS with K8s version <= `0.22`.

@bartoszkosciug Closing this issue as we are unable to reproduce this.
Feel free to re-open if you could share the steps to reproduce the same using latest helm chart.

**Closed by prashant-shahi** 2022-10-31 14:09 UTC
