### ISSUE TITLE
Open query builder UI by default when creating new alert

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2876] opened 2023-06-09 02:40 UTC
Clickhouse builder UI is opened by default when user tries to create an alert, since query builder is easier to use and will be more frequently used so opening query builder UI will save one more click of user

**Comment by srikanthccv** [comment] 2023-06-09 02:48
Duplicate of https://github.com/SigNoz/signoz/issues/2868

**Closed** 2023-06-09 02:51 UTC
Labels: alerts
