### ISSUE TITLE
iRate not working in PromQL query builder

### ISSUE THREAD

**Issue by makeavish** [SigNoz/signoz#2902] opened 2023-06-14 11:15 UTC
In some servers (not all) the iRate function is not giving any results, though rate works fine.

**Comment by srikanthccv** [comment] 2024-08-28 07:35
It occurred on a specific tenant in the past and we could not reproduce it later. Closing for now. We will troubleshoot if it surfaces up again.

**Closed by srikanthccv** 2024-08-28 07:35 UTC
Labels: bug, dashboards
