### ISSUE TITLE
Alert has issues when use time shift  & formula

### ISSUE THREAD

**Issue by chensunny** [SigNoz/signoz#6151] opened 2024-10-10 02:04 UTC
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

Alert has issues when use time shift  & formula likes. it works well in Dashboard but wrong is alert.
![image](https://github.com/user-attachments/assets/adfd0896-6690-4a9d-a8a0-e939e4d81fb8)

## How to reproduce

![image](https://github.com/user-attachments/assets/adfd0896-6690-4a9d-a8a0-e939e4d81fb8)

## Version information 
* **Signoz version**:
v0.48
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel): 
Intel

## Additional context

I think because Dashboard use v4 api and Alert use v3 API (edited) 
Can you change the alert to V4 API？？

**Comment by ahmadshaheer** [comment] 2024-10-13 12:06
@chensunny, can you please share the response formats in case of alerts and dashboards? 

@srikanthccv, can you please help me how to reproduce this issue based on the data in staging environment?

**Comment by chensunny** [comment] 2024-10-14 05:58
https://signoz.automizely.org/api/v1/testRule

```
{"id":"74","state":"disabled","alert":"test-alert","alertType":"LOGS_BASED_ALERT","ruleType":"threshold_rule","evalWindow":"24h0m0s","frequency":"1m0s","condition":{"compositeQuery":{"builderQueries":{"A":{"dataSource":"logs","queryName":"A","aggregateOperator":"count","aggregateAttribute":{"key":"","dataType":"","type":"","isColumn":false,"isJSON":false,"id":"------false"},"timeAggregation":"count","spaceAggregation":"sum","functions":[{"name":"timeShift","args":["604800"]}],"filters":{"items":[{"id":"cbb12c76","key":{"key":"org.contract.type","dataType":"string","type":"tag","isColumn":false,"isJSON":false},"op":"=","value":"Enterprise terms"},{"id":"34cbffc4","key":{"key":"service.name","dataType":"string","type":"resource","isColumn":true,"isJSON":false},"op":"=","value":"prod-oc.as-in.com_biz-monitoring-production"},{"id":"2a5430b3","key":{"key":"event","dataType":"string","type":"tag","isColumn":true,"isJSON":false},"op":"=","value":"processed"},{"id":"e8d75260","key":{"key":"event.name","dataType":"string","type":"tag","isColumn":true,"isJSON":false},"op":"=","value":"omnichannel/email_event"}],"op":"AND"},"expression":"A","disabled":true,"stepInterval":43200,"having":[],"limit":0,"orderBy":[],"groupBy":[{"key":"org.id","dataType":"string","type":"tag","isColumn":true,"isJSON":false,"id":"org.id--string--tag--true"}],"legend":"","reduceTo":"avg","offset":0,"pageSize":0,"ShiftBy":86400},"B":{"dataSource":"logs","queryName":"B","aggregateOperator":"count","aggregateAttribute":{"key":"","dataType":"","type":"","isColumn":false,"isJSON":false,"id":"------false"},"timeAggregation":"count","spaceAggregation":"sum","functions":[],"filters":{"items":[{"id":"387c4f1c","key":{"key":"org.contract.type","dataType":"string","type":"tag","isColumn":false,"isJSON":false},"op":"=","value":"Enterprise terms"},{"id":"1890c54e","key":{"key":"service.name","dataType":"string","type":"resource","isColumn":true,"isJSON":false},"op":"=","value":"prod-oc.as-in.com_biz-monitoring-production"},{"id":"97f8901b","key":{"key":"event","dataType":"string","type":"tag","isColumn":true,"isJSON":false},"op":"=","value":"processed"},{"id":"e358ee93","key":{"key":"event.name","dataType":"string","type":"tag","isColumn":true,"isJSON":false},"op":"=","value":"omnichannel/email_event"}],"op":"AND"},"expression":"B","disabled":true,"stepInterval":43200,"having":[],"limit":0,"orderBy":[],"groupBy":[{"key":"org.id","dataType":"string","type":"tag","isColumn":true,"isJSON":false,"id":"org.id--string--tag--true"}],"legend":"","reduceTo":"avg","offset":0,"pageSize":0,"ShiftBy":0},"F1":{"queryName":"F1","expression":"(B-A)/A","disabled":false,"legend":"","stepInterval":6,"dataSource":"","aggregateOperator":"","aggregateAttribute":{"key":"","dataType":"","type":"","isColumn":false,"isJSON":false},"limit":0,"offset":0,"pageSize":0,"ShiftBy":0}},"promQueries":{"A":{"name":"A","query":"","legend":"","disabled":false}},"chQueries":{"A":{"name":"A","legend":"","disabled":false,"query":""}},"queryType":"builder","panelType":"graph"},"op":"1","target":20,"absentFor":30,"matchType":"1","selectedQueryName":"F1"},"labels":{"severity":"warning","testing":"yes"},"annotations":{"description":"This alert is fired when the defined metric (current value: {{$value}}) crosses the threshold ({{$threshold}})","summary":"The rule threshold is set to {{$threshold}}, and the observed metric value is {{$value}}"},"disabled":true,"source":"https://signoz.automizely.org/alerts/edit?search=&columnKey=severity&order=null&page=6&compositeQuery=%257B%2522builder%2522%253A%257B%2522queryData%2522%253A%255B%257B%2522dataSource%2522%253A%2522logs%2522%252C%2522queryName%2522%253A%2522A%2522%252C%2522aggregateOperator%2522%253A%2522count%2522%252C%2522aggregateAttribute%2522%253A%257B%2522key%2522%253A%2522%2522%252C%2522dataType%2522%253A%2522%2522%252C%2522type%2522%253A%2522%2522%252C%2522isColumn%2522%253Afalse%252C%2522isJSON%2522%253Afalse%257D%252C%2522timeAggregation%2522%253A%2522count%2522%252C%2522spaceAggregation%2522%253A%2522sum%2522%252C%2522functions%2522%253A%255B%257B%2522name%2522%253A%2522timeShift%2522%252C%2522args%2522%253A%255B%2522604800%2522%255D%257D%255D%252C%2522filters%2522%253A%257B%2522op%2522%253A%2522AND%2522%252C%2522items%2522%253A%255B%257B%2522key%2522%253A%257B%2522key%2522%253A%2522org.contract.type%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522tag%2522%252C%2522isColumn%2522%253Afalse%252C%2522isJSON%2522%253Afalse%257D%252C%2522value%2522%253A%2522Enterprise%2520terms%2522%252C%2522op%2522%253A%2522%253D%2522%257D%252C%257B%2522key%2522%253A%257B%2522key%2522%253A%2522service.name%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522resource%2522%252C%2522isColumn%2522%253Atrue%252C%2522isJSON%2522%253Afalse%257D%252C%2522value%2522%253A%2522prod-oc.as-in.com_biz-monitoring-production%2522%252C%2522op%2522%253A%2522%253D%2522%257D%252C%257B%2522key%2522%253A%257B%2522key%2522%253A%2522event%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522tag%2522%252C%2522isColumn%2522%253Atrue%252C%2522isJSON%2522%253Afalse%257D%252C%2522value%2522%253A%2522processed%2522%252C%2522op%2522%253A%2522%253D%2522%257D%252C%257B%2522key%2522%253A%257B%2522key%2522%253A%2522event.name%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522tag%2522%252C%2522isColumn%2522%253Atrue%252C%2522isJSON%2522%253Afalse%257D%252C%2522value%2522%253A%2522omnichannel%252Femail_event%2522%252C%2522op%2522%253A%2522%253D%2522%257D%255D%257D%252C%2522expression%2522%253A%2522A%2522%252C%2522disabled%2522%253Atrue%252C%2522stepInterval%2522%253A43200%252C%2522having%2522%253A%255B%255D%252C%2522limit%2522%253A0%252C%2522orderBy%2522%253A%255B%255D%252C%2522groupBy%2522%253A%255B%257B%2522key%2522%253A%2522org.id%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522tag%2522%252C%2522isColumn%2522%253Atrue%252C%2522isJSON%2522%253Afalse%257D%255D%252C%2522legend%2522%253A%2522%2522%252C%2522reduceTo%2522%253A%2522avg%2522%252C%2522offset%2522%253A0%252C%2522pageSize%2522%253A0%252C%2522ShiftBy%2522%253A86400%257D%252C%257B%2522dataSource%2522%253A%2522logs%2522%252C%2522queryName%2522%253A%2522B%2522%252C%2522aggregateOperator%2522%253A%2522count%2522%252C%2522aggregateAttribute%2522%253A%257B%2522key%2522%253A%2522%2522%252C%2522dataType%2522%253A%2522%2522%252C%2522type%2522%253A%2522%2522%252C%2522isColumn%2522%253Afalse%252C%2522isJSON%2522%253Afalse%257D%252C%2522timeAggregation%2522%253A%2522count%2522%252C%2522spaceAggregation%2522%253A%2522sum%2522%252C%2522functions%2522%253A%255B%255D%252C%2522filters%2522%253A%257B%2522op%2522%253A%2522AND%2522%252C%2522items%2522%253A%255B%257B%2522key%2522%253A%257B%2522key%2522%253A%2522org.contract.type%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522tag%2522%252C%2522isColumn%2522%253Afalse%252C%2522isJSON%2522%253Afalse%257D%252C%2522value%2522%253A%2522Enterprise%2520terms%2522%252C%2522op%2522%253A%2522%253D%2522%257D%252C%257B%2522key%2522%253A%257B%2522key%2522%253A%2522service.name%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522resource%2522%252C%2522isColumn%2522%253Atrue%252C%2522isJSON%2522%253Afalse%257D%252C%2522value%2522%253A%2522prod-oc.as-in.com_biz-monitoring-production%2522%252C%2522op%2522%253A%2522%253D%2522%257D%252C%257B%2522key%2522%253A%257B%2522key%2522%253A%2522event%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522tag%2522%252C%2522isColumn%2522%253Atrue%252C%2522isJSON%2522%253Afalse%257D%252C%2522value%2522%253A%2522processed%2522%252C%2522op%2522%253A%2522%253D%2522%257D%252C%257B%2522key%2522%253A%257B%2522key%2522%253A%2522event.name%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522tag%2522%252C%2522isColumn%2522%253Atrue%252C%2522isJSON%2522%253Afalse%257D%252C%2522value%2522%253A%2522omnichannel%252Femail_event%2522%252C%2522op%2522%253A%2522%253D%2522%257D%255D%257D%252C%2522expression%2522%253A%2522B%2522%252C%2522disabled%2522%253Atrue%252C%2522stepInterval%2522%253A43200%252C%2522having%2522%253A%255B%255D%252C%2522limit%2522%253A0%252C%2522orderBy%2522%253A%255B%255D%252C%2522groupBy%2522%253A%255B%257B%2522key%2522%253A%2522org.id%2522%252C%2522dataType%2522%253A%2522string%2522%252C%2522type%2522%253A%2522tag%2522%252C%2522isColumn%2522%253Atrue%252C%2522isJSON%2522%253Afalse%257D%255D%252C%2522legend%2522%253A%2522%2522%252C%2522reduceTo%2522%253A%2522avg%2522%252C%2522offset%2522%253A0%252C%2522pageSize%2522%253A0%252C%2522ShiftBy%2522%253A0%257D%255D%252C%2522queryFormulas%2522%253A%255B%257B%2522queryName%2522%253A%2522F1%2522%252C%2522expression%2522%253A%2522%28B-A%29%252FA%2522%252C%2522disabled%2522%253Afalse%252C%2522legend%2522%253A%2522%2522%252C%2522stepInterval%2522%253A6%252C%2522dataSource%2522%253A%2522%2522%252C%2522aggregateOperator%2522%253A%2522%2522%252C%2522aggregateAttribute%2522%253A%257B%2522key%2522%253A%2522%2522%252C%2522dataType%2522%253A%2522%2522%252C%2522type%2522%253A%2522%2522%252C%2522isColumn%2522%253Afalse%252C%2522isJSON%2522%253Afalse%257D%252C%2522limit%2522%253A0%252C%2522offset%2522%253A0%252C%2522pageSize%2522%253A0%252C%2522ShiftBy%2522%253A0%257D%255D%257D%252C%2522promql%2522%253A%255B%257B%2522query%2522%253A%2522%2522%252C%2522disabled%2522%253Afalse%252C%2522name%2522%253A%2522A%2522%257D%255D%252C%2522clickhouse_sql%2522%253A%255B%257B%2522query%2522%253A%2522%2522%252C%2522disabled%2522%253Afalse%252C%2522name%2522%253A%2522A%2522%257D%255D%252C%2522queryType%2522%253A%2522builder%2522%252C%2522id%2522%253A%252215c4044c-de04-475c-b62f-dbd9652fcd64%2522%257D&panelTypes=graph&ruleId=74&relativeTime=2w","preferredChannels":["Brandy - Accounts - Low"],"version":"v4","createAt":"2024-10-10T07:21:13.131539072Z","createBy":"hc.cai@aftership.com","updateAt":"2024-10-12T10:10:47.897436189Z","updateBy":"hc.cai@aftership.com","broadcastToAll":false}

```

**Comment by srikanthccv** [comment] 2024-10-14 08:07
> [signoz.automizely.org/api/v1/testRule](https://signoz.automizely.org/api/v1/testRule)
> 
> another issue, it will test fail if there is a multiplication or a departure in `formula` !!!
> 
> ```
> (B-A)/A
> ```

@chensunny please be a little more descriptive about the problem. It's not possible to understand what you mean by this.

**Comment by srikanthccv** [comment] 2024-10-14 08:10
> can you please help me how to reproduce this issue based on the data in staging environment?

I will share loom video.

**Comment by kobecal** [comment] 2024-10-16 07:02
It's easy to reproduce this issue. Here's an example process to reproduce.
1. A query timeshift by 86400, groupby any field
2. B query is same config with A query except for timeshift.(No need timeshift in B query)
3. F1: B-A
Then, you will find the F1 result is wrong.
Three reasons result in this issue.
First, the query should be` v4/query_range`, v3/query_range is totally wrong if we calculate the week-over-week day-over-day data. 
Add `"version":"v4" `to alert rule should fix the issue in panel.
But it's not fixed in alert. 
The second reason is that the query A will not prepare ShiftBy field. So A and B query will request same time range data.
Assign a correct ShiftBy should the query issue.
For now. The issue issue is still not fixed.
The third reason is postProcess functions need to align timeshift A query result. Then the A and B  query result can be calculated at same timestamp value. 
timeShift functions value should updated to 86400 from "86400"

**Comment by kobecal** [comment] 2024-10-18 02:51
The PR https://github.com/SigNoz/signoz/pull/6209 can only fix the alert panel issue. But the alert with timeshift functions is still not good, because the timeshift is not calculated correctly when evaluating alert rule in backend.

**Comment by srikanthccv** [comment] 2024-10-18 05:28
> The third reason is postProcess functions need to align timeshift A query result

https://github.com/SigNoz/signoz/blob/204728ff60346c906dbf13b7a53d99bf585a2be4/pkg/query-service/app/queryBuilder/functions.go#L312

https://github.com/SigNoz/signoz/blob/204728ff60346c906dbf13b7a53d99bf585a2be4/pkg/query-service/postprocess/process.go#L36

**Comment by srikanthccv** [comment] 2024-10-18 05:28
> But the alert with timeshift functions is still not good, because the timeshift is not calculated correctly when evaluating alert rule in backend

What do you mean by this? Please elaborate!

**Comment by kobecal** [comment] 2024-10-21 08:28
> > But the alert with timeshift functions is still not good, because the timeshift is not calculated correctly when evaluating alert rule in backend
> 
> What do you mean by this? Please elaborate!
`{"functions":[{"name":"timeShift","args":[604800]}]}`
The query range API will process the timeShift function and calculate the time shift value and assign to ShiftBy. According to the ShiftBy value, the start and end time of the query will be re-calculated.
But when running alert rule, The ShiftBy is always 0. Because the timeShift function is never executed. 
So A and B query will get same result even their timeShift functions configs are different.

**Comment by srikanthccv** [comment] 2024-10-21 13:48
You are correct. We will fix that bug as well.

**Closed** 2024-10-28 06:22 UTC
Labels: bug
