### ISSUE TITLE
Get rid of the "Click a widget icon to  ..." panel in the final dashboard layout #nicetohave

### ISSUE THREAD

**Issue by polyglothacker** [SigNoz/signoz#722] opened 2022-02-13 10:21 UTC
## Is your feature request related to a problem? No

Let us say I want to add an even number of panels and make my dashboard look nice. Since signoz always adds the `Click to add widget here` panel even in the final layout this is not possible. Even becomes odd - odd becomes even. 

## Describe the solution you'd like

Get rid of the `Click a widget icon to add it here` in the final dashboard layout. It really should come only on the Dashboard Edit view.

## Describe alternatives you've considered

Well - always add an odd number of panels so this comes as the last one and "evens" everything out.
![signoz_layout](https://user-images.githubusercontent.com/97145793/153748742-2036b817-c0fd-4f81-b2b7-1898817c348c.jpg)

**Comment by pranay01** [comment] 2022-02-13 11:19
@polyglothacker Thanks for opening the issue. Just trying to understand this better, is this concern just from a visual cleanliness point of view or there are some functional issues caused by it? Do you intend to project these dashboards on a monitors etc. which developers would also visually monitor? 

As of now we don't have a construct of edit/view mode in dashboard. The section which shows the panel is by default editable.

**Comment by polyglothacker** [comment] 2022-02-14 06:32
Visual cleanliness and finish. Think of it as - if my wall is painted I dont want to see a paintbrush on the corner ?

**Comment by pranay01** [comment] 2022-09-14 07:55
this is fixed now in the latest versions

**Closed by pranay01** 2022-09-14 07:55 UTC
Labels: frontend, dashboards, ideas
