### ISSUE TITLE
LOGS[FE]: Going back to list view doesn't remove group by

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz#5135] opened 2024-06-03 11:15 UTC
Going back to list view doesn't remove group by

https://github.com/SigNoz/signoz/assets/26831659/f4400132-d45d-450b-a7ba-9cc419e552e4

**Comment by srikanthccv** [comment] 2024-06-11 19:18
This should be fixed. I ran into this and it was not clear what the issue is unless I open dev tools. Even with dev tools, one won't be able to figure out without the knowledge of aggregate operators in the query builder. We should fix this bug because seeing the count and switching to a list is a common task.

**Comment by YounixM** [comment] 2024-06-19 06:09
@nityanandagohain @srikanthccv : As discussed, assigning it back to you as it will be handled in BE.

**Closed** 2024-06-19 10:10 UTC
Labels: bug
