### ISSUE TITLE
Bug in Query Builder Search

### ISSUE THREAD

**Issue by Calm-Rock** [SigNoz/signoz#3650] opened 2023-09-28 09:59 UTC
## Bug description

Please checkout this [video](https://www.loom.com/share/0bf90929961d4fd9b5f3cc49c95cd6b9?sid=b8392dfd-0c31-4e22-90a9-a8831a5981f7)

## Expected behavior
Ideally the search should display the command I'm typing after I have selected the attribute I want to filter with.

## How to reproduce

1. Open SigNoz cloud instance or local instance
2. Go to logs section 
3. Search in a query 

## Version information 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**: MacOS Ventura
* **Your CPU Architecture**(ARM/Intel): ARM

**Comment by srikanthccv** [comment] 2023-09-29 00:48
Duplicate of https://github.com/SigNoz/signoz/issues/3585

**Closed** 2023-11-30 05:28 UTC
