### ISSUE TITLE
Cluttering of text in gantt chart

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/signoz#442] opened 2021-12-03 04:38 UTC
![Screenshot 2021-12-03 at 10 07 39 AM](https://user-images.githubusercontent.com/12460410/144546136-54d43860-1aba-4df0-b53a-46f5a15a943f.png)

**Comment by Anurag5086** [comment] 2021-12-05 07:14
@ankitnayan Can you help me reproduce it, because at my end i don't see the cluttering of text.

**Comment by pranay01** [comment] 2022-03-03 13:47
fixed by https://github.com/SigNoz/signoz/pull/764 - Updated trace detail page design

**Closed by pranay01** 2022-03-03 13:47 UTC
Labels: frontend, trace-detail-page, ui
