### ISSUE TITLE
If a TTL request fails - the save button is disabled

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz#1828] opened 2022-12-07 14:12 UTC
If a TTL request fails - the save button is disabled. This will leave users in a hung state if TTL setting failed. 

Expected Behavior:

Save Button should not be disabled so that users can try again

version: v0.12-rc1

![set-ttl](https://user-images.githubusercontent.com/504541/206201438-74cc1b4a-7b21-40be-8a5d-239694a336b3.png)

**Comment by makeavish** [comment] 2023-01-27 06:32
Duplicate of https://github.com/SigNoz/signoz/issues/1830

**Closed by makeavish** 2023-01-27 06:32 UTC
Labels: duplicate, ttl
