### ISSUE TITLE
Port conflicts while installing SigNoz

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#580] opened 2021-11-30 13:47 UTC
User had some process running on `port 8080` which is used by SigNoz query service.

He got confused and mentioned SigNoz only uses `port 3000`. 

Possible solution:
mention in docs all the ports SigNoz needs for running

**Comment by ankitnayan** [comment] 2022-01-03 18:35
Duplicate of #166

**Closed by ankitnayan** 2022-01-03 18:35 UTC
