### ISSUE TITLE
The alarm cannot be triggered according to the specified rule.

### ISSUE THREAD

**Issue by cxposition** [SigNoz/signoz#6684] opened 2024-12-20 03:16 UTC
## Bug description
Set memory alarms. The alarm rules are as follows:
![Image](https://github.com/user-attachments/assets/a7f55b76-6153-4b33-a073-4dc94c275c08)
The corresponding alarm chart is as follows:
![Image](https://github.com/user-attachments/assets/b1ecc9b6-419b-42ef-a36b-2212554d94ae)
In this case, alarms are recorded only when the alarm is created and when the query-service service is restarted. It is unknown whether the fault is caused by the alarm rule configuration or back-end code processing. The alarm history is as follows:
![Image](https://github.com/user-attachments/assets/29f6f595-0680-4375-bae4-6ed2d1a644cd)

## Expected behavior
When the threshold is always greater than the alarm value, a message is periodically sent to the channel.

## How to reproduce

1.Create a webhook channel.
2.Create metrics-based memory alarms.
3.Observe the alarm triggering frequency and webhook email sending.

## Version information 
* **Signoz version**: 0.61.0
* **Browser version**: 131.0.6778.140(chrome)
* **Your OS and version**: centos7
* **Your CPU Architecture**(ARM/Intel): intel

**Comment by srikanthccv** [comment] 2024-12-20 17:50
>When the threshold is always greater than the alarm value, a message is periodically sent to the channel.

When the alert moves to the firing state, a notification will be sent, now, if the alert still remains in the firing, no new notification will be sent for the next repeat interval (4 hours). This is expected behaviour, as your value is always above the threshold.

**Comment by cxposition** [comment] 2024-12-24 02:11
> > When the threshold is always greater than the alarm value, a message is periodically sent to the channel.
> 
> When the alert moves to the firing state, a notification will be sent, now, if the alert still remains in the firing, no new notification will be sent for the next repeat interval (4 hours). This is expected behaviour, as your value is always above the threshold.

Thank you very much for your answer.

**Comment by srikanthccv** [comment] 2024-12-24 04:12
Closing since your question is answered.

**Closed by srikanthccv** 2024-12-24 04:12 UTC
