### ISSUE TITLE
Color difference in side panel on light mode

### ISSUE THREAD

**Issue by ankit01-oss** [SigNoz/signoz#918] opened 2022-03-25 12:07 UTC
In light mode, the section above support has a different color than the section that starts from `support` 
<img width="207" alt="Screenshot 2022-03-25 at 5 37 08 PM" src="https://user-images.githubusercontent.com/83692067/160117856-96ea98e5-8414-4636-962b-2a7963fb3f6c.png">

**Comment by makeavish** [comment] 2022-11-17 05:54
This is duplicate of https://github.com/SigNoz/signoz/issues/866
Closing it

**Closed by makeavish** 2022-11-17 05:54 UTC
Labels: frontend
