### ISSUE TITLE
Not able to view/access service dashboard, application is crashing

### ISSUE THREAD

**Issue by 2dev2** [SigNoz/signoz#3615] opened 2023-09-24 12:54 UTC
## Bug description

we are able to nevigate trace and log dashboard its working fine.
In service section we can see service listed there.
Once we click on servicename and go to particular service dashboard, then application is crashing.
<img width="1792" alt="Screenshot 2023-09-24 at 6 15 05 PM" src="https://github.com/SigNoz/signoz/assets/8681544/f7d45341-72d7-4efe-b6f2-eb4e5bb063d2">
<img width="1792" alt="Screenshot 2023-09-24 at 6 15 18 PM" src="https://github.com/SigNoz/signoz/assets/8681544/d9f547ce-6e84-4704-b641-52cb7e0825fb">

## Expected behavior
specific Service dashboard should load property.
if any error occur it should not affect the whole application only part of dashboard should not load.

## How to reproduce

1. Go to list of services
2. go to specific  service dashboard
3. Application got crashed.

## Version information 
* **Signoz version**:  v0.29.3
* **Browser version**: chrome  Version 116.0.5845.187 (Official Build) (x86_64)
* **Your OS and version**: MacOS ventura 13.5.2 
* **Your CPU Architecture**(ARM/Intel): intel

## Additional context

Attaching screenshot so that we can see workflow correctly.
https://github.com/SigNoz/signoz/assets/8681544/f03ae246-8014-40bd-ad98-7c6746f64cf3

**Comment by srikanthccv** [comment] 2023-09-24 13:33
Duplicate of https://github.com/SigNoz/signoz/issues/3583. @palashgdev is trying to troubleshoot this, but he can't replicate it and needs help. @2dev2 will you be able to get on a call sometime tomorrow and help us debug since this is happening for specific client environments?

**Comment by palashgdev** [comment] 2023-09-24 14:32
yes @2dev2 it would be great help to resolve asap

**Comment by 2dev2** [comment] 2023-09-24 16:01
Hi if needed we can connect today also . otherwise i will be able to connect tomorrow evening time around 6 PM IST

**Comment by palashgdev** [comment] 2023-09-25 04:58
> Hi @palashgdev if needed we can connect today also. otherwise, i will be able to connect tomorrow evening time around 6 PM IST

can you share your mail id

**Comment by 2dev2** [comment] 2023-10-01 13:40
My Email id is dharmadev2@gmail.com, please schedule call.

**Comment by svsk417** [comment] 2023-10-13 12:58
Hi, I have looked into this a little further. We expierience the same issue. I thinke that I have found the root cause of this: 
- In https://github.com/SigNoz/signoz/blob/develop/frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetricsApplication.tsx#L27C4-L27C4 there is a null coalescing operator on data, so metricsBucket can become null
- Inhttps://github.com/SigNoz/signoz/blob/develop/frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetrics.tsx#L79 there is a variable `isQueryEnabled`which becomes null, when metricsBuckets is null
- This is passed to the Graph component in https://github.com/SigNoz/signoz/blob/develop/frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetrics.tsx#L91
- This makes it down to this enabled property https://github.com/SigNoz/signoz/blob/develop/frontend/src/container/GridCardLayout/GridCard/index.tsx#L78, which then becomes null 

Bear with me, if I am wrong, I far away from being a JavaScript expert

**Comment by svsk417** [comment] 2023-10-13 13:02
@palashgdev just comment, if you need any screen shots. I can provide these, if you wish. :)

**Comment by palashgdev** [comment] 2023-10-14 18:55
hi @svsk417 
Thanks for sharing your insights 

would it possible to share the pr

**Comment by svsk417** [comment] 2023-10-16 06:11
Hi @palashgdev,
I have just looked into what is going wrong. I didn't "fix" the issue since I do not know what kind of implications might come with it.

**Closed** 2023-11-06 06:46 UTC
