### ISSUE TITLE
Clone Dashboard

### ISSUE THREAD

**Issue by marcoberri** [SigNoz/signoz#6294] opened 2024-10-28 09:20 UTC
## Describe the solution you'd like
Hi,

it would be very useful to have an action to perform a clone of the dashboard in order to make configuration faster without rewriting all the variable configurations

![image](https://github.com/user-attachments/assets/a3fbc453-1d1c-482a-a81f-592422436fa9)

tnx

## Describe alternatives you've considered
For clone the configuration I open two tabs in browser and i copy and paste che info but is a very slowly operation with many variables

tnx

**Comment by mohamed-ikram-zepto** [comment] 2024-12-24 10:13
hi @YounixM @srikanthccv can you please assign to me i want to contribute

**Comment by srikanthccv** [comment] 2024-12-26 04:38
Hi @mohamed-ikram-zepto, this is a duplicate of https://github.com/SigNoz/signoz/issues/6298 and has been implemented already in https://github.com/SigNoz/signoz/pull/6595. Hence, closing. Please find another open issue.

**Closed by srikanthccv** 2024-12-26 04:38 UTC
Labels: good first issue, dashboards, user-experience (ux)
