### ISSUE TITLE
FE: Changing the global time hangs the UI for some amount of time 

### ISSUE THREAD

**Issue by palashgdev** [SigNoz/signoz#2122] opened 2023-01-25 15:03 UTC
@csudani7 Can you please check this behaviour?
https://www.loom.com/share/c990f425c1a049539d2a473b5ec98b41

_Originally posted by @makeavish in https://github.com/SigNoz/signoz/issues/2068#issuecomment-1403372065_

**Comment by csudani7** [comment] 2023-01-31 04:11
@makeavish & @srikanthccv Not able to reproduce in latest develop branch. I tried with below custom parameters.
Please visit: https://www.loom.com/share/724102a8671b488d85f74aa0b8ea1ee3
Can you confirm this?

CC: @palashgdev

**Comment by MastersAbh** [comment] 2023-01-31 14:09
Can you assign this to me ?

**Comment by palashgdev** [comment] 2023-01-31 15:59
Sure @MastersAbh

**Comment by makeavish** [comment] 2023-02-07 05:27
@csudani7 Not able to reproduce this issue.
@MastersAbh Were you able to reproduce?

**Comment by MastersAbh** [comment] 2023-02-11 10:18
Hey, No. This seems to be working properly now. 
@palashgdev can you check again ?

**Comment by makeavish** [comment] 2023-02-14 09:47
Closing the issue as it's not reproducible

**Closed by makeavish** 2023-02-14 09:47 UTC
Labels: bug, good first issue, frontend, p2
