### ISSUE TITLE
Alert labels are not stored

### ISSUE THREAD

**Issue by patrijua** [SigNoz/signoz#2692] opened 2023-05-15 07:54 UTC
## Bug description

When creating a new alert, labels are not stored.

For example, creating an alert with label abc: xyz

<img width="783" alt="image" src="https://github.com/SigNoz/signoz/assets/57624530/fc302c42-3dd9-41c6-834a-1c972059a59c">

When alert is saved, there are no labels for the alert:

<img width="1493" alt="image" src="https://github.com/SigNoz/signoz/assets/57624530/bcb17918-ad7e-4ac4-87d9-ca63df51c378">

## Expected behavior

Labels should be saved.

## Version information 
* **Signoz version**: v0.18.3
* **Browser version**: Chrome 113.0.5672.92 
* **Your OS and version**: MacOS Ventura 13.1
* **Your CPU Architecture**(ARM/Intel): Intel

**Comment by palashgdev** [comment] 2023-05-15 08:26
Hi @patrijua is this always the case or after refresh values come? as recently one of the [pr](https://github.com/SigNoz/signoz/pull/2671) is merged against such an issue

**Comment by patrijua** [comment] 2023-05-15 11:11
Hi @palashgdev is always the same, refresh does not help.

**Comment by Damans227** [comment] 2023-06-10 01:06
Hi @palashgdev, I too was able to reproduce the issue. You can watch[ the recording here](https://www.loom.com/share/a4ea5efc0cd04e9d8e0306ce0a4a0b24). Just to make sure, I waited for 10-15 minutes after creating those alerts, but the labels did not appear.

I would like to work on this problem, if that's okay with you.

**Comment by pranay01** [comment] 2023-06-10 05:03
Sure, assigned it to you @Damans227

**Comment by Damans227** [comment] 2023-06-10 13:38
So I have done some investigation and at this point I'm unsure if it's a frontend issue. 

`allAlertRules` prop ([passed down to the ListAlert.tsx](https://github.com/SigNoz/signoz/blob/develop/frontend/src/container/ListAlertRules/ListAlert.tsx#L29)) which must contain the labels and other data to be displayed in alerts lists, does not contain the label that is set when creating an alert. Below is a screenshot. 

![Screenshot-6](https://github.com/SigNoz/signoz/assets/61474540/40661d3a-b994-498c-83cf-ef2732422898)


Now if I hard code an object with a label in `allAlertRules` prop, it just shows up fine. 

![Screenshot-5](https://github.com/SigNoz/signoz/assets/61474540/fe2939be-38b1-475b-8deb-eb172d782ba7)


Thus, I am considering doing some API testing on the following endpoint.

**Comment by Damans227** [comment] 2023-06-10 13:40
When trying to access `http://localhost:3301/api/v1/rules` I get the following error: 

```
{"status":"error","errorType":"unauthorized","error":"failed to parse jwt token: token contains an invalid number of segments"}

```

Any idea how can I get past this? I am authenticated to the query-service. So, not sure why I am unauthorised to access the api.

**Comment by Damans227** [comment] 2023-06-10 14:53
It is also possible that the labels are not being captured when the data is saved on the form after clicking on the create rule button. In any case, I am digging deeper into this and it would still be useful to know how I can access the backend API. Thank you!

**Comment by Damans227** [comment] 2023-06-10 15:09
It looks like what I said above is exactly the cause of the problem. Form data for labels is not being captured. In the create rule form, I can hardcode a label and it gets saved correctly.[ Loom video](https://www.loom.com/share/259f2e41c9254b79b3d03c3d453c3c0d) of the root cause.

**Comment by Damans227** [comment] 2023-06-10 16:25
This appears to be a design quirk/user error, not a defect. It appears that the user typed the key and value together as a key, when they should have done it one at a time as per the prompt shown in label input dialog. 

The following screen recordings demonstrate how to create labels correctly and incorrectly. 

- [Correct way to create a label](https://www.loom.com/share/9d153bdcecb742b897dc8375392bf381)
- [Incorrect way to create a label](https://www.loom.com/share/6097a1ae67ae479583575a15da8adacc)

**Comment by Damans227** [comment] 2023-06-10 16:31
I have marked the user error in the original test case error submitted by @patrijua 

![user_error](https://github.com/SigNoz/signoz/assets/61474540/d7f4bb58-5b41-45b7-97a5-d8424628b03a)

**Comment by Damans227** [comment] 2023-06-10 16:36
As an enhancement, we can ask the user to provide a value for the key instead of silently rejecting an invalid key. This also raises the question of whether we want to allow colons or other special characters in the key. 

@pranay01 @palashgdev @srikanthccv Awaiting your response. Thx!

**Comment by Damans227** [comment] 2023-06-10 18:41
An option to allow ending a key or value string with a colon, along with the existing option to press enter, may prevent this confusion. I've implemented this in [ my PR.](https://github.com/SigNoz/signoz/pull/2886).

**Closed** 2023-06-12 09:06 UTC
Labels: frontend, alerts
