### ISSUE TITLE
Why the "Status Code" col is empty when the status code is not 200? And the "Rate (ops/s)", "Error Percentage", "ApDex" dashboard all empty?

### ISSUE THREAD

**Issue by nengc** [SigNoz/signoz#3998] opened 2023-11-20 06:38 UTC
## Bug description

![image](https://github.com/SigNoz/signoz/assets/19792047/823d1670-57b6-4770-8b2b-eb0ca394d88c)

I used the repo "https://github.com/SigNoz/sample-golang-app"

![image](https://github.com/SigNoz/signoz/assets/19792047/1af9b8be-4962-41f2-b99d-5f5acff7ba1c)

![image](https://github.com/SigNoz/signoz/assets/19792047/67c6c38d-1bac-47a9-95b9-133bd3a0ac6e)

![image](https://github.com/SigNoz/signoz/assets/19792047/89d45e19-aac1-42b3-9d88-b73158b83dd2)

## How to reproduce

1.
2.
3.

## Version information 
* **Signoz version**: 4083970
* **Browser version**:
* **Your OS and version**:
* **Your CPU Architecture**(ARM/Intel):

**Comment by dirtyren** [comment] 2023-11-20 12:37
I am having the same problem, some show and others dont show status code. I am using  Odigos do auto instrument my go apps.
Tks.

**Comment by ankitnayan** [comment] 2023-11-20 14:07
>And the "Rate (ops/s)", "Error Percentage", "ApDex" dashboard all empty? 

Looking at the charts posted, it seems there is no consistent load to the applications. The mentioned charts work on metrics and need continuous data to work on. Try giving consistent load to the applications for 5 mins and let us know if the charts do not show up.
Another reason could be the `otel-collector-metrics` service is not running or is throwing errors. But I suspect the inconsistent load to be the reason in your case.

@makeavish might want to look into the `status_code` issue

**Comment by nengc** [comment] 2023-11-21 01:48
Hi, @ankitnayan thanks for your reply. I tested again with consistent load, but still empty. And the ``otel-collector-metrics `` service is running without throwing errors.
![image](https://github.com/SigNoz/signoz/assets/19792047/10f5c8d2-ae47-4e77-9975-6030177a4826)
![image](https://github.com/SigNoz/signoz/assets/19792047/0856c277-9a06-4bf6-8f0c-d14a6445237a)
![image](https://github.com/SigNoz/signoz/assets/19792047/1f77f65f-ffa9-44ac-93ad-60ff429c8e1d)
![image](https://github.com/SigNoz/signoz/assets/19792047/e54b9a57-7056-4040-ac14-c92085843d86)

**Comment by makeavish** [comment] 2023-11-21 05:32
@nengc I am using latest https://github.com/SigNoz/sample-golang-app and SigNoz [v.34.0](https://github.com/SigNoz/signoz/releases/tag/v0.34.0) and services page worked fine for me.
<img width="1284" alt="Screenshot 2023-11-21 at 10 59 31" src="https://github.com/SigNoz/signoz/assets/9512100/ac24a17a-84ce-464a-ae70-1dc91c6447be">

**Comment by nengc** [comment] 2023-11-21 05:57
@makeavish I am also using`` https://github.com/SigNoz/sample-golang-app`` and SigNoz [develop f4ecfb5]. And with the config same as ``https://github.com/SigNoz/signoz/blob/develop/deploy/docker/clickhouse-setup/otel-collector-config.yaml`` and ``https://github.com/SigNoz/signoz/blob/develop/deploy/docker/clickhouse-setup/otel-collector-metrics-config.yaml``.

And the i searched the metrics from the dashboard and only find the metric "signoz_latency_milliseconds_***".
But i found the http request with the params "signoz_latency_count".

![image](https://github.com/SigNoz/signoz/assets/19792047/6fb6d0bf-28ed-4ee1-a83c-9306d8564823)
![image](https://github.com/SigNoz/signoz/assets/19792047/b5c9dc43-7037-42cd-8e22-c009a9923df0)
![image](https://github.com/SigNoz/signoz/assets/19792047/b26f8b10-4c2a-4b54-bfd3-11e2d1610930)
![image](https://github.com/SigNoz/signoz/assets/19792047/47c612fb-8c90-4ffc-9f44-8425fa518f7d)

**Comment by makeavish** [comment] 2023-11-21 06:00
Regarding the http status code, `c.JSON(http.StatusBadRequest, gin.H{"error": "Record not found!"})` is overriding http status code to 400. so you need to set `c.JSON(http.StatusInternalServerError, gin.H{"error": "Record not found!"})`


<img width="911" alt="Screenshot 2023-11-21 at 11 27 59" src="https://github.com/SigNoz/signoz/assets/9512100/f2d9444e-7bc0-440d-b7b5-8d57d6b58734">

**Comment by makeavish** [comment] 2023-11-21 06:01
Also there seems to be some issue with Error Percentage graph I am investigating it.

**Comment by makeavish** [comment] 2023-11-21 06:36
> Also there seems to be some issue with Error Percentage graph I am investigating it.

Error Percentage graph issue is due to NaN values and will be fixed by https://github.com/SigNoz/signoz/issues/3999

**Comment by nengc** [comment] 2023-11-21 06:42
@makeavish Tks, the Error Percentage graph  works well now. But Rate (ops/s), ApDex still have no data. Need any other customized config?

**Comment by makeavish** [comment] 2023-11-21 06:55
> @makeavish Tks, the Error Percentage graph works well now. But Rate (ops/s), ApDex still have no data. Need any other customized config?

I tried on new signoz instance as well and all graphs are working fine as shared in previous screenshot (Except for some minor issue related to NaN values)

Can you try on fresh SigNoz instance?

**Comment by nengc** [comment] 2023-11-21 07:20
Hi @makeavish , I used the latest version but Rate (ops/s), ApDex still have no data.  And Database Calls also empty. 

![image](https://github.com/SigNoz/signoz/assets/19792047/e9faadb2-d421-467b-8daf-c0372612a93a)
![image](https://github.com/SigNoz/signoz/assets/19792047/580af838-c5e0-4e83-8263-6cec77ee8379)

**Comment by nengc** [comment] 2023-11-21 07:27
And ``Status Code`` still empty

![image](https://github.com/SigNoz/signoz/assets/19792047/c062d8f8-e995-4365-8f35-03cac9620058)
![image](https://github.com/SigNoz/signoz/assets/19792047/d9b2d32c-d521-4625-b4b2-fa2d06f618c8)

**Comment by nengc** [comment] 2023-11-21 09:16
@makeavish after I deleted all the database and use the latest code, the graphs works. But the ``Status Code`` still empty.
![image](https://github.com/SigNoz/signoz/assets/19792047/05577abd-7688-47cb-98b1-a24fb2745b83)
![image](https://github.com/SigNoz/signoz/assets/19792047/ba8d99c8-82dc-4b88-a727-80793825de25)

**Comment by makeavish** [comment] 2023-11-21 13:34
> Regarding the http status code, `c.JSON(http.StatusBadRequest, gin.H{"error": "Record not found!"})` is overriding http status code to 400. so you need to set `c.JSON(http.StatusInternalServerError, gin.H{"error": "Record not found!"})`

Did you try this?
https://github.com/SigNoz/signoz/issues/3998#issuecomment-1820290233

If you are still facing issue then can you join [SigNoz community](https://signoz.io/slack) on slack and ask there?

**Comment by makeavish** [comment] 2023-11-22 10:43
Closing this as some issues mentioned are fixed and other issues are not reproducible

**Closed by makeavish** 2023-11-22 10:43 UTC

**Comment by nengc** [comment] 2023-11-23 08:57
I found that if i added `` defer span.End() ``, the ``Status Code`` would be empty. After i deleted the `` defer span.End() ``, it works fine. Tks
